<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
  /**  
  * The table associated with the model.
  * 
  * @var string
  */
  protected $table='users';
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'integer',
    'name'=>'string',
    'email'=>'string',
    'email_verified_at'=>'datetime',
    'password'=>'string',
    'remember_token'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
}
